/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#faf9ff",
        "surface-dim": "#d7d9e7",
        "surface-bright": "#faf9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#ebedfb",
        "surface-container-high": "#e5e8f5",
        "surface-container-highest": "#dfe2ef",
        "on-surface": "#181b25",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#2c303a",
        "inverse-on-surface": "#eef0fe",
        "outline": "#76767e",
        "outline-variant": "#c6c6ce",
        "surface-tint": "#565d79",
        "surface-variant": "#dfe2ef",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#131a33",
        "on-primary-container": "#7b83a0",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#bec5e5",
        "on-primary-fixed": "#131a33",
        "on-primary-fixed-variant": "#3e4660",
        "inverse-primary": "#bec5e5",
        "secondary": "#0051d5",
        "on-secondary": "#ffffff",
        "secondary-container": "#316bf3",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a1700",
        "on-tertiary-container": "#b87500",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "background": "#faf9ff",
        "on-background": "#181b25",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.125rem",
        "md": "0.375rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "max-content-width": "1280px",
        "max-reading-width": "680px"
      },
      fontFamily: {
        "headline-xl": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "body-lead": ["Newsreader", "serif"],
        "display-hero": ["Newsreader", "serif"],
        "display-hero-mobile": ["Newsreader", "serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "label-data": ["Geist", "monospace", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"]
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lead": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-data": ["13px", { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
